export { default as Github } from './Github'
export { default as Instagram } from './Instagram'
export { default as Linkedin } from './Linkedin'
export { default as Note } from './Note'
export { default as Twitter } from './Twitter'
export { default as Youtube } from './Youtube'
